name: Update Renovate Branch

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-renovate-branch:
    if: github.event.pull_request.head.repo.full_name == github.repository && startsWith(github.head_ref, 'renovate/') && github.actor == 'renovate[bot]'
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: '5'
      EARTHLY_INSTALL_ID: 'actions-setup'
    steps:
      - uses: EarthBuild/actions-setup@main
        with:
          version: v0.8.16
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.head_ref }}
      - name: Build
        run: earth --ci --output +compile
      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist
          if git diff --staged --quiet; then
            echo "nothing to commit"
          else
            git commit -m "ci: update dist for Renovate"
          fi
          git push
