name: 'Test action-install-earth'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  unit:
    name: earth +all
    permissions:
      contents: read
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: '5'
      EARTHLY_INSTALL_ID: 'earthbuild-actions-setup-githubactions'
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Docker Hub mirrors
        run: |
          echo '{"registry-mirrors": ["https://mirror.gcr.io", "https://public.ecr.aws"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: '24.14.0'
      - uses: ./
      - run: earth --secret GITHUB_TOKEN +all
  # Below are tests specific to the github actions, which ensure the actions-setup code works with GHA
  latest:
    name: Test Latest Version Install
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: '24.14.0'
      - run: npm install
      - run: npm run package
      - uses: ./
      - run: earth --version
  specific:
    name: Test Specific Version Install
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: '24.14.0'
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: 0.8.17
      - run: earth --version
  patch-range:
    name: Test Patch Range Version Install
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: '24.14.0'
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: 0.8.*
      - run: earth --version
  major-range:
    name: Test Patch Range Version Install
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version: '24.14.0'
      - run: npm install
      - run: npm run package
      - uses: ./
        with:
          version: ^0.8.17
      - run: earth --version
