name: Update Major Version Branch

on:
  release:
    types: [released]

permissions: {}

jobs:
  update-major-version-branch:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: '5'
      EARTHLY_INSTALL_ID: 'earthly-actions-setup-githubactions'
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.8.6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.ref }}
      - name: Update Branch
        run: earthly --ci -P --push +merge-release-to-major-branch --RELEASE_TAG=${{ github.ref }}
